# Generated by Django 3.2.5 on 2023-08-26 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('content', models.TextField(verbose_name='文档内容')),
                ('url', models.URLField(verbose_name='文档链接')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='最近修改时间')),
                ('team', models.DateTimeField(verbose_name='所属团队')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.user', verbose_name='创建者')),
            ],
        ),
    ]
