# Generated by Django 3.2.5 on 2023-08-29 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.TextField(null=True, verbose_name='文档内容'),
        ),
    ]
