# Generated by Django 4.2.4 on 2023-08-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='isLocked',
            field=models.BooleanField(default=False, verbose_name='是否上锁'),
        ),
        migrations.AddField(
            model_name='document',
            name='url_editable',
            field=models.URLField(null=True, verbose_name='可编辑链接'),
        ),
        migrations.AlterField(
            model_name='document',
            name='url',
            field=models.URLField(null=True, verbose_name='不可编辑文档链接'),
        ),
    ]
