# Generated by Django 3.2.5 on 2023-08-31 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20230830_1912'),
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_private',
            field=models.BooleanField(default=True, verbose_name='是否私有'),
        ),
        migrations.AddField(
            model_name='document',
            name='is_template',
            field=models.BooleanField(default=False, verbose_name='是否为模板'),
        ),
        migrations.AddField(
            model_name='prototype',
            name='is_private',
            field=models.BooleanField(default=True, verbose_name='是否私有'),
        ),
        migrations.AddField(
            model_name='prototype',
            name='is_template',
            field=models.BooleanField(default=False, verbose_name='是否为模板'),
        ),
        migrations.AlterField(
            model_name='document',
            name='parent_folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='document.folder', verbose_name='所属文件夹'),
        ),
        migrations.AlterField(
            model_name='document',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='prototype',
            name='content',
            field=models.TextField(null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='prototype',
            name='parent_folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='document.folder', verbose_name='所属文件夹'),
        ),
        migrations.AlterField(
            model_name='prototype',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='创建者'),
        ),
    ]
