# Generated by Django 3.2.5 on 2023-08-26 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='url',
            field=models.URLField(null=True, verbose_name='文档链接'),
        ),
    ]
