# Generated by Django 3.2.5 on 2023-08-27 19:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='team',
        ),
        migrations.RemoveField(
            model_name='prototype',
            name='team',
        ),
        migrations.AddField(
            model_name='document',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='team.project', verbose_name='所属项目'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prototype',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='team.project', verbose_name='所属项目'),
            preserve_default=False,
        ),
    ]
