# Generated by Django 3.2.5 on 2023-08-29 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_alter_document_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True, verbose_name='文档内容')),
                ('modified_at', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='document.document')),
            ],
            options={
                'ordering': ['-modified_at'],
            },
        ),
    ]
