# Generated by Django 4.2.4 on 2023-08-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_document_islocked_document_url_editable_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='isLocked',
            new_name='is_locked',
        ),
        migrations.AddField(
            model_name='document',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否被删除'),
        ),
    ]
