# Generated by Django 3.2.5 on 2023-08-31 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_auto_20230831_1943'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Copy',
        ),
    ]
