# Generated by Django 3.2.5 on 2023-08-26 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_team_cover_url'),
        ('document', '0002_alter_document_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='team.team', verbose_name='所属团队'),
        ),
    ]
