# Generated by Django 3.2.5 on 2023-08-30 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20230830_1112'),
        ('user', '0003_alter_user_avatar_url'),
        ('document', '0003_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='prototype',
            name='token',
            field=models.URLField(null=True, verbose_name='预览原型链接'),
        ),
        migrations.AddField(
            model_name='prototype',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='是否可见'),
        ),
        migrations.AlterField(
            model_name='document',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.project', verbose_name='所属项目'),
        ),
        migrations.AlterField(
            model_name='document',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='history',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.document'),
        ),
        migrations.AlterField(
            model_name='prototype',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.project', verbose_name='所属项目'),
        ),
        migrations.AlterField(
            model_name='prototype',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='创建者'),
        ),
    ]
