# Generated by Django 4.2.4 on 2023-08-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_delete_copy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='url',
        ),
        migrations.RemoveField(
            model_name='document',
            name='url_editable',
        ),
        migrations.AddField(
            model_name='document',
            name='editable',
            field=models.BooleanField(default=True, verbose_name='是否可编辑'),
        ),
    ]
