# Generated by Django 4.2.4 on 2023-08-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_prototype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='is_locked',
            field=models.IntegerField(default=False, verbose_name='文件锁'),
        ),
    ]
