# Generated by Django 3.2.5 on 2023-08-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='prototype',
            name='length',
            field=models.DecimalField(decimal_places=2, default=1920, max_digits=10),
        ),
        migrations.AddField(
            model_name='prototype',
            name='width',
            field=models.DecimalField(decimal_places=2, default=1080, max_digits=10),
        ),
    ]
