# Generated by Django 3.2.5 on 2023-09-01 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_project_cover_url'),
        ('document', '0005_history_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='is_locked',
        ),
        migrations.AddField(
            model_name='document',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='team.project', verbose_name='模板所属项目'),
        ),
        migrations.AddField(
            model_name='prototype',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='team.project', verbose_name='模板所属项目'),
        ),
    ]
