# Generated by Django 3.2.5 on 2023-08-25 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='未命名团队', max_length=10, verbose_name='团队名称')),
                ('description', models.CharField(max_length=10, null=True, verbose_name='团队描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('invitation', models.URLField(null=True, verbose_name='邀请链接')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='创建者')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CR', '创建者'), ('MG', '管理者'), ('MB', '普通成员')], default='MB', max_length=2)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='team.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.user', verbose_name='成员')),
            ],
        ),
    ]
