# Generated by Django 4.2.4 on 2023-08-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='cover_url',
            field=models.URLField(default='https://summer-1315620690.cos.ap-beijing.myqcloud.com/team_cover/default.png', verbose_name='团队封面'),
        ),
    ]
