# Generated by Django 3.2.5 on 2023-08-29 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='invitation',
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=20, verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.CharField(max_length=50, null=True, verbose_name='团队描述'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(default='未命名团队', max_length=20, verbose_name='团队名称'),
        ),
    ]
