# Generated by Django 3.2.5 on 2023-08-25 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, verbose_name='项目创建时间')),
                ('name', models.CharField(max_length=10, verbose_name='项目名称')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='team.team', verbose_name='所属团队')),
            ],
        ),
    ]
