# Generated by Django 3.2.5 on 2023-08-26 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='cover_url',
            field=models.URLField(default=1, verbose_name='团队封面'),
            preserve_default=False,
        ),
    ]
