# Generated by Django 4.2.4 on 2023-08-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_alter_team_cover_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
    ]
