# Generated by Django 3.2.5 on 2023-08-27 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_current_team_id'),
        ('team', '0003_team_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='user.user', verbose_name='创建者'),
            preserve_default=False,
        ),
    ]
