# Generated by Django 4.2.4 on 2023-08-31 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_alter_member_user_alter_team_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deleted_at',
            field=models.DateTimeField(null=True, verbose_name='被删除时间'),
        ),
    ]
