# Generated by Django 3.2.5 on 2023-09-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_remove_team_is_real'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cover_url',
            field=models.URLField(default='https://summer-1315620690.cos.ap-beijing.myqcloud.com/team_cover/1.png', verbose_name='头像封面'),
            preserve_default=False,
        ),
    ]
