# Generated by Django 4.2.4 on 2023-08-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userteamchatstatus',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userteamchatstatus',
            name='is_at',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userteamchatstatus',
            name='is_at_all',
            field=models.BooleanField(default=False),
        ),
    ]
