# Generated by Django 4.2.4 on 2023-08-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='is_real',
        ),
        migrations.AddField(
            model_name='team',
            name='actual_team',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='is_private',
            field=models.BooleanField(default=True, verbose_name='是否为私聊'),
        ),
    ]
