# Generated by Django 4.2.4 on 2023-08-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='files',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='reply_message',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(default=None),
        ),
    ]
