# Generated by Django 4.2.4 on 2023-08-30 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_avatar_url'),
        ('chat', '0002_remove_team_is_real_team_actual_team_team_is_private'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='Group',
        ),
    ]
