# Generated by Django 4.2.4 on 2023-08-27 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_current_team_id'),
        ('chat', '0002_userteamchatstatus_index_userteamchatstatus_is_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChatChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=255, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
