# Generated by Django 4.2.4 on 2023-08-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatmessage_forwarded_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='forwarded_from',
            field=models.ManyToManyField(blank=True, to='chat.chatmessage'),
        ),
    ]
