# Generated by Django 4.2.4 on 2023-08-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_rename_member_chatmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='是否为私聊'),
        ),
    ]
