# Generated by Django 4.2.4 on 2023-08-31 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chatmessage_forwarded_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='progress',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='data',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
