# Generated by Django 4.2.4 on 2023-08-31 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_file_progress_chatmessage_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='data',
            new_name='date',
        ),
    ]
