# Generated by Django 4.2.4 on 2023-09-01 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_rename_data_chatmessage_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='type',
            field=models.CharField(default='file', max_length=10, verbose_name='文件类型'),
        ),
    ]
