# Generated by Django 4.2.4 on 2023-08-31 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_chatmessage_forwarded_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='文件地址')),
                ('name', models.CharField(max_length=50, verbose_name='文件名')),
                ('audio', models.BooleanField(default=False, verbose_name='是否为音频')),
                ('duration', models.IntegerField(default=0, verbose_name='音频时长')),
                ('size', models.IntegerField(default=0, verbose_name='文件大小')),
                ('preview', models.URLField(default=None, null=True, verbose_name='文件预览地址')),
                ('progress', models.IntegerField(default=0, verbose_name='文件上传进度')),
                ('chat_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatmessage')),
            ],
        ),
    ]
