# Generated by Django 4.2.4 on 2023-09-01 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.CharField(max_length=50, verbose_name='文件类型'),
        ),
    ]
