# Generated by Django 4.2.4 on 2023-09-01 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20230830_1912'),
        ('chat', '0010_alter_chatmessage_forwarded_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='user1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_group_as_user1', to='user.user'),
        ),
        migrations.AddField(
            model_name='group',
            name='user2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_group_as_user2', to='user.user'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='forwarded_from',
            field=models.ManyToManyField(blank=True, to='chat.chatmessage'),
        ),
    ]
