# Generated by Django 3.2.9 on 2023-07-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, verbose_name='用户名')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('password', models.CharField(max_length=16, verbose_name='账户密码')),
                ('avatar_url', models.CharField(default='', max_length=128, verbose_name='头像地址')),
                ('description', models.CharField(default='', max_length=128, verbose_name='签名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('isActive', models.BooleanField(default=False, max_length=10, verbose_name='是否有效账户')),
            ],
        ),
    ]
