# Generated by Django 3.2.5 on 2023-08-26 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='消息标题')),
                ('content', models.CharField(max_length=100, verbose_name='消息具体内容')),
                ('url', models.URLField(verbose_name='跳转链接')),
            ],
        ),
    ]
