# Generated by Django 3.2.5 on 2023-08-30 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20230829_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(default='https://summer-1315620690.cos.ap-beijing.myqcloud.com/user_avatar/default.png', verbose_name='头像路径'),
        ),
    ]
