# Generated by Django 3.2.5 on 2023-08-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_avatar_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.AddField(
            model_name='user',
            name='is_new',
            field=models.BooleanField(default=True, verbose_name='是否为新用户'),
        ),
    ]
