name: Django_deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: pull and reload on Aliyun
        run: sshpass -p ${{secrets.ESC_TOKEN}} ssh -o StrictHostKeyChecking=no root@${{secrets.ECS_IP}} "git pull --force; git checkout main;"